In [2]:
#import modules
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np

In [7]:
iris  = load_iris()
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
#train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.3)

**Logistic Regression**

In [9]:
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

0.9555555555555556

**SVM**

In [10]:
svm = SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9777777777777777

**Random Forest**

In [16]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

1.0

**DecisionTree Classifier**

In [12]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
dt.score(X_test, y_test)

0.9555555555555556

<h2 style='color:purple'>KFold cross validation</h2>

In [36]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [37]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


**Use KFold for our digits example**

In [38]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [39]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_dt = []
scores_rf = []

for train_index, test_index in folds.split(iris.data,iris.target):
    X_train, X_test, y_train, y_test = iris.data[train_index], iris.data[test_index], \
                                       iris.target[train_index], iris.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))
    scores_dt.append(get_score(DecisionTreeClassifier(), X_train, X_test, y_train, y_test))

In [40]:
scores_logistic

[0.96, 0.96, 0.94]

In [56]:
np.average(scores_logistic)

0.9533333333333333

In [41]:
scores_svm

[0.98, 0.98, 0.96]

In [57]:
np.average(scores_svm)

0.9733333333333333

In [42]:
scores_dt

[0.98, 0.92, 1.0]

In [58]:
np.average(scores_dt)

0.9666666666666667

In [59]:
scores_rf

[0.98, 0.94, 0.96]

In [60]:
np.average(scores_rf)

0.96

Best İs SVM

<h2 style='color:red'>cross_val_score function</h2>


In [44]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [45]:
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), iris.data, iris.target,cv=3)

array([0.96, 0.96, 0.94])

**svm model performance using cross_val_score**

In [47]:
cross_val_score(SVC(gamma='auto'), iris.data, iris.target,cv=3)

array([0.98, 0.98, 0.96])

**random forest performance using cross_val_score**

In [48]:
cross_val_score(RandomForestClassifier(n_estimators=40),iris.data, iris.target,cv=3)

array([0.98, 0.94, 0.96])

**Decision Tree  performance using cross_val_score**

In [50]:
cross_val_score(DecisionTreeClassifier(),iris.data, iris.target,cv=3)

array([0.98, 0.92, 0.98])

<h2 style='color:purple'>Parameter tunning using k fold cross validation</h2>


In [51]:
scores1 = cross_val_score(RandomForestClassifier(n_estimators=5),iris.data, iris.target, cv=10)
np.average(scores1)

0.9466666666666667

In [52]:
scores2 = cross_val_score(RandomForestClassifier(n_estimators=15),iris.data, iris.target, cv=10)
np.average(scores2)

0.9666666666666666

In [53]:
scores3 = cross_val_score(RandomForestClassifier(n_estimators=30),iris.data, iris.target, cv=10)
np.average(scores3)

0.9533333333333334

In [54]:
scores4 = cross_val_score(RandomForestClassifier(n_estimators=40),iris.data, iris.target, cv=10)
np.average(scores4)

0.9666666666666666

In [55]:
scores5 = cross_val_score(RandomForestClassifier(n_estimators=50),iris.data, iris.target, cv=10)
np.average(scores5)

0.96

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.